# src/docs/swaggerDef.yaml (VERSÃO COMPLETA)

tags:
  - name: NFS-e
    description: Emissão de Nota Fiscal de Serviço eletrônica

paths:
  /emitir-nfse:
    post:
      summary: Emite uma nova NFS-e
      tags: [NFS-e]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NfsInput'
      responses:
        '201':
          description: NFS-e emitida com sucesso.
        '400':
          description: Erro nos dados de entrada ou falha de validação da API do governo.
        '500':
          description: Erro interno do servidor ou na comunicação com a API do governo.

components:
  schemas:
    NfsInput:
      type: object
      # ... (A definição do NfsInput que vou colocar na Parte 2 irá aqui)
      # Por enquanto, manteremos a estrutura anterior para corrigir o erro.
      required:
        - idDps
        - prestador
        - tomador
        - servico
      properties:
        idDps:
          type: string
          description: "Um identificador único para o DPS (Ex: dps_cliente_xyz_001)"
        prestador:
          type: object
          properties:
            cnpj:
              type: string
            inscricaoMunicipal:
              type: string
        tomador:
          type: object
          properties:
            documento:
              type: string
            razaoSocial:
              type: string
            endereco:
              type: object
              properties:
                logradouro:
                  type: string
                numero:
                  type: string
                bairro:
                  type: string
                codigoMunicipio:
                  type: string
                uf:
                  type: string
                cep:
                  type: string
        servico:
          type: object
          properties:
            codigo:
              type: string
            discriminacao:
              type: string
            codigoMunicipio:
              type: string
            valor:
              type: number
      example:
        idDps: "dps_cliente_xyz_001"
        prestador:
          cnpj: "00111222000133"
        tomador:
          documento: "33444555000166"
          razaoSocial: "EMPRESA TOMADORA LTDA"
          endereco:
            logradouro: "AV BRIGADEIRO FARIA LIMA"
            numero: "1500"
            bairro: "JARDIM PAULISTANO"
            codigoMunicipio: "3550308"
            uf: "SP"
            cep: "01452-002"
        servico:
          codigo: "01.07"
          discriminacao: "Consultoria em TI"
          codigoMunicipio: "3550308"
          valor: 2500.50