# src/docs/swaggerDef.yaml

tags:
  - name: NFS-e
    description: Emissão de Nota Fiscal de Serviço eletrônica

paths:
  /emitir-nfse:
    post:
      summary: Emite uma nova Nota Fiscal de Serviço Eletrônica
      tags: [NFS-e]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NfsInput'
      responses:
        '201':
          description: NFS-e emitida com sucesso.
        '400':
          description: Erro nos dados de entrada ou falha de validação da API do governo.
        '500':
          description: Erro interno do servidor ou na comunicação com a API do governo.

components:
  schemas:
    NfsInput:
      type: object
      required: # <-- AQUI DEFINIMOS OS CAMPOS OBRIGATÓRIOS
        - dps
        - prestador
        - tomador
        - servico
      properties:
        dps:
          type: object
          required: [serie, numero, dataCompetencia]
          properties:
            serie: { type: string, example: "1" }
            numero: { type: number, example: 35 }
            dataCompetencia: { type: string, format: "date", example: "2025-08-06" }
        prestador:
          type: object
          required: [cnpj, codigoMunicipio]
          properties:
            cnpj: { type: string, example: "51512249000117" }
            codigoMunicipio: { type: string, example: "4115200" }
            inscricaoMunicipal: { type: string, example: "123456" }
            razaoSocial: { type: string, example: "ARTHUR DUARTE ZACARIAS" }
        tomador:
          type: object
          required: [documento, razaoSocial, endereco]
          properties:
            documento: { type: string, example: "05389061000106" }
            razaoSocial: { type: string, example: "BIOESSENCIA FARMACIA DE MANIPULACAO LTDA" }
            nomeFantasia: { type: string, example: "BIOESSENCIA" }
            endereco:
              type: object
              required: [logradouro, numero, bairro, codigoMunicipio, uf, cep]
              properties:
                logradouro: { type: string, example: "RUA ACCIOLLY FILHO" }
                numero: { type: string, example: "655-B" }
                bairro: { type: string, example: "Centro" }
                codigoMunicipio: { type: string, example: "4113502" }
                uf: { type: string, example: "PR" }
                cep: { type: string, example: "87900000" }
                complemento: { type: string, example: "Sala 01" }
            contato:
              type: object
              properties:
                telefone: { type: string, example: "44999998888" }
                email: { type: string, example: "contato@bioessencia.com.br" }
        intermediario:
          type: object
          properties:
            documento: { type: string, example: "11222333000144" }
            razaoSocial: { type: string, example: "EMPRESA INTERMEDIARIA LTDA" }
            inscricaoMunicipal: { type: string, example: "789012" }
        servico:
          type: object
          required: [itemListaServico, discriminacao, codigoMunicipioPrestacao, valor]
          properties:
            itemListaServico: { type: string, example: "01.07" }
            codigoTributacaoMunicipio: { type: string, example: "12345" }
            discriminacao: { type: string, example: "Desenvolvimento de API completa" }
            codigoMunicipioPrestacao: { type: string, example: "4115200" }
            valor: { type: number, example: 1500.50 }
        valores:
          type: object
          properties:
            valorDeducoes: { type: number, example: 100.00 }
            valorPis: { type: number, example: 10.00 }
            descontoIncondicionado: { type: number, example: 50.00 }
            iss:
              type: object
              properties:
                aliquota: { type: number, example: 2.00 }
                valor: { type: number, example: 27.00 }
                retido: { type: boolean, example: true }